CREATE TABLE EMPLOYEE (	ID INT NOT NULL,
 						NAME VARCHAR(32) NOT NULL,
 						OFFICE VARCHAR(32) NOT NULL,
 						AGE SMALLINT NOT NULL,
 						PRIMARY KEY(ID),
 						CHECK(AGE BETWEEN 0 AND 100));

CREATE TABLE BOOK (	ID INT NOT NULL,
					NAME VARCHAR(32) NOT NULL,
					AUTHOR VARCHAR(32) NOT NULL,
					PUBLISHER VARCHAR(32) NOT NULL,
					PRIMARY KEY(ID));

CREATE TABLE RECORD (	BOOK_ID INT NOT NULL,
						EMPLOYEE_ID INT NOT NULL,
						TIME DATE NOT NULL,
						FOREIGN KEY(BOOK_ID) REFERENCES BOOK(ID),
						FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
						PRIMARY KEY(BOOK_ID,EMPLOYEE_ID));
